// Prueba de la vista real en Chromium mediante CDP, con servidor de sala controlado.
const assert = require('node:assert/strict');
const express = require('express');
const http = require('node:http');
const {once} = require('node:events');
const {spawn} = require('node:child_process');
const {mkdtempSync} = require('node:fs');
const {rm} = require('node:fs/promises');
const {tmpdir} = require('node:os');
const path = require('node:path');
const WebSocket = require('ws');
let state = {salaId:'room',secuencia:5,numeroActual:5,numerosExtraidos:[1,2,3,4,5],bolillas:[1,2,3,4,5],ronda:0,
 modo:'BINGO',titulo:'Bingo de prueba',rangoMax:90,estado:'EN_CURSO',conteos:{},sorteoBingoId:null,timestamp:new Date().toISOString()};
const liveOnly = process.argv.includes('--live-only');
const app = express();app.use(express.json());let registrations=0,lastClaim=null;
const testCard={id:'card-2',posicion:2,contenido:[[1,2,3,4,5,null,null,null,null],[6,7,8,9,10,null,null,null,null],[11,12,13,14,15,null,null,null,null]]};
app.post('/auth/registro',(_q,r)=>{registrations++;r.json({mensaje:'Cuenta creada'});});
app.get('/auth/me',(_q,r)=>r.json({id:'org',nombre:'Prueba',email:'prueba@example.test',rol:'ORGANIZADOR',estado:'APROBADO'}));
app.get('/sorteos',(_q,r)=>r.json(liveOnly?[{id:'bingo',tipo:'BINGO',linkToken:'bingo',titulo:'Prueba'}]:[]));app.get('/eventos-en-vivo',(_q,r)=>r.json(liveOnly?[{id:'room',sorteoBingoId:'bingo',linkToken:'token'}]:[]));
app.get('/eventos-en-vivo/room',(_q,r)=>r.json({...state,id:'room',linkToken:'token'}));
let published=null;app.post('/eventos-en-vivo/room/mensaje',(q,r)=>{published=q.body;r.json({comunidad:{espectadores:23,aviso:{id:'org-message',texto:q.body.texto,expiraEn:Date.now()+8000}}});});
const pagos=[];
const reservas={numeros:'RESERVADO',series:'RESERVADO'};
app.get('/sorteos/pagos/:tipo',(q,r)=>r.json({tipo:q.params.tipo==='numeros'?'RIFA':'BINGO',titulo:'Pagos',estado:'ACTIVO',tablero:[{valor:1,numero:1,cantidadCartones:1,estado:reservas[q.params.tipo],participante:{nombre:'Titular Prueba',dni:'12345678',telefono:'123456789'}}]}));
app.patch('/sorteos/pagos/:tipo/:numero',(q,r)=>{pagos.push(q.body);reservas[q.params.tipo]=q.body.estado;r.json({});});
app.post('/vivo/:token/mis-series',(q,r)=>{assert.deepEqual(q.body,{dni:'12345678'});r.json({series:[1,2].map(numeroSerie=>({numeroSerie,marcas:{},cartones:Array.from({length:6},(_,i)=>({...testCard,id:'card-'+i,posicion:i+1}))}))});});
app.post('/vivo/:token/cantar',(q,r)=>{lastClaim=q.body;state={...state,secuencia:state.secuencia+1,estado:'PAUSADO',cantos:[{tipo:q.body.tipo,numeroSerie:2,numeroCarton:2,participante:'Ana <script>',carton:testCard}],historialGanadores:[...(state.historialGanadores||[]),{tipo:q.body.tipo,numeroSerie:2,numeroCarton:2,participante:'Ana <script>'}]};r.json({type:'STATE_SNAPSHOT',...state});});
let resetRequests=0, resetFails=false;const mutationOrder=[];
app.post('/eventos-en-vivo/room/extraer',async(_q,r)=>{
  await new Promise(resolve=>setTimeout(resolve,250));
  mutationOrder.push('extraer');state={...state,secuencia:state.secuencia+1,numeroActual:21,numerosExtraidos:[...state.numerosExtraidos,21],bolillas:[...state.numerosExtraidos,21],estado:'EN_CURSO'};
  r.json({tablero:state});
});
app.post('/eventos-en-vivo/room/reiniciar',(_q,r)=>{
  resetRequests++;if(resetFails)return r.status(503).json({error:'Servidor no disponible'});
  mutationOrder.push('reiniciar');state={...state,secuencia:state.secuencia+1,ronda:state.ronda+1,numeroActual:null,numerosExtraidos:[],bolillas:[],cantos:[],historialGanadores:[],estado:'EN_CURSO'};
  r.json(state);
});
app.get('/vivo/:token',(_q,r)=>r.set('Cache-Control','no-store').json({type:'STATE_SNAPSHOT',...state}));
app.use(express.static(path.resolve(__dirname,'../frontend')));
(async()=>{
 const server = http.createServer(app);const wss = new WebSocket.WebSocketServer({server,path:'/ws'});let connections=0;
 wss.on('connection',ws=>{connections++;ws.on('message',raw=>{const msg=JSON.parse(raw);if(msg.type==='RESYNC')ws.send(JSON.stringify({type:'STATE_SNAPSHOT',...state}));if(msg.type==='PING')ws.send(JSON.stringify({type:'PONG'}));});});
 server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;
 const profile = mkdtempSync(path.join(tmpdir(),'bingo-live-'));
 const chrome=spawn(process.env.CHROMIUM_PATH || '/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
 let ws;
 try {
 const debuggerUrl=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(new Error('Chromium no inició')),15000);chrome.stderr.on('data',chunk=>{output+=chunk;const m=output.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1]);}});chrome.on('error',reject);});
 const debugBase=new URL(debuggerUrl).origin.replace('ws:','http:');const targets=await (await fetch(debugBase+'/json')).json();
 ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await once(ws,'open');let id=0;const calls=new Map(),errors=[];
 ws.on('message',raw=>{const m=JSON.parse(raw);if(m.id){calls.get(m.id)?.(m);calls.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);});
 const cmd=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;calls.set(key,m=>m.error?reject(m.error):resolve(m.result));ws.send(JSON.stringify({id:key,method,params}));});
 const evaluate=async expression=>{const r=await cmd('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=async expr=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await new Promise(r=>setTimeout(r,100));}throw new Error('Timeout '+expr);};
 await cmd('Page.enable');await cmd('Runtime.enable');await cmd('Network.enable');
 await cmd('Page.addScriptToEvaluateOnNewDocument',{source:`window.locuciones=[];window.speechSynthesis.speak=u=>{window.ultimaLocucion=u;window.locuciones.push(u.text);};window.speechSynthesis.cancel=()=>{};`});
 await cmd('Page.navigate',{url:base+'/sorteo-en-vivo.html?modo=espectador&sorteo=token'});
 await wait('document.getElementById("currentBall")?.textContent === "05" && document.getElementById("conexionEnVivo").textContent === "En vivo"');
 assert.equal(await evaluate('document.querySelectorAll("#board .called").length'),5);
 assert.equal(await evaluate('document.getElementById("currentBall").classList.contains("pop")'),false);
 assert.equal(await evaluate('document.querySelectorAll("#cage .mini-ball").length'),85);
 assert.equal(await evaluate('[...document.querySelectorAll("#cage .mini-ball")].some(b=>b.dataset.numero==="5")'),false);
 assert.equal(await evaluate('new Set([...document.querySelectorAll("#cage .mini-ball")].map(b=>b.dataset.numero)).size'),85);
 console.log('OK: recarga/entrada tardía muestra la última bolilla e historial completo sin animación.');
 await cmd('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});
 await evaluate('window.dispatchEvent(new Event("offline"))');
 for(const client of wss.clients)client.terminate();
 state={...state,secuencia:10,numeroActual:10,numerosExtraidos:[1,2,3,4,5,6,7,8,9,10],bolillas:[1,2,3,4,5,6,7,8,9,10]};
 await wait('document.getElementById("conexionEnVivo").textContent.includes("Sin conexión")');
 assert.equal(await evaluate('document.getElementById("currentBall").textContent'),'05');
 assert.equal(await evaluate('document.getElementById("boardPanel").dataset.desactualizado'),'true');
 await cmd('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await evaluate('window.dispatchEvent(new Event("online"))');
 await wait('document.getElementById("currentBall").textContent === "10" && document.getElementById("conexionEnVivo").textContent === "En vivo"');
 assert.equal(await evaluate('document.getElementById("currentBall").classList.contains("pop")'),false);
 assert.equal(await evaluate('document.querySelectorAll("#cage .mini-ball").length'),80);
 console.log('OK: cinco extracciones sin Internet conservan tablero y se recuperan completas sin animación.');
 state={...state,secuencia:11,numeroActual:11,numerosExtraidos:[...state.numerosExtraidos,11]};
 // No broadcast: comprobar el respaldo HTTP real a cinco segundos.
 await wait('document.getElementById("currentBall").textContent === "11"');
 assert.equal(await evaluate('document.querySelectorAll("#board .called").length'),11);
 console.log('OK: HTTP de respaldo actualiza el DOM aunque no llegue ningún mensaje WS.');
 state={...state,secuencia:12,ronda:1,numeroActual:null,numerosExtraidos:[],bolillas:[],inicioProgramado:'2030-01-02T12:00:00Z'};
 await evaluate('window.dispatchEvent(new Event("focus"))');await wait('document.getElementById("currentBall").textContent === "esperando"');
 assert.equal(await evaluate('document.querySelectorAll("#board .called").length'),0);
 assert.equal(await evaluate('document.querySelectorAll("#cage .mini-ball").length'),90);
 await wait('!document.getElementById("cuentaRegresivaVivo").hidden');
 state={...state,inicioProgramado:null};await evaluate('window.dispatchEvent(new Event("focus"))');
 await wait('document.getElementById("cuentaRegresivaVivo").hidden');
 console.log('OK: resincronización limpia tablero; la fecha aparece y se puede quitar sin extraer bolillas.');
 const count=connections;await evaluate('window.dispatchEvent(new PageTransitionEvent("pagehide",{persisted:true}))');
 await new Promise(r=>setTimeout(r,100));assert.equal(wss.clients.size,0);
 await evaluate('window.dispatchEvent(new PageTransitionEvent("pageshow",{persisted:true}))');
 await wait('document.getElementById("conexionEnVivo").textContent === "En vivo"');assert.equal(connections,count+1);assert.equal(wss.clients.size,1);
 console.log('OK: pagehide/pageshow cierra y restaura una única conexión.');
 assert.deepEqual(await evaluate('window.locuciones'),[]);
 assert.equal(await evaluate('document.getElementById("sonidoBolillero")'),null);
 state={...state,secuencia:13,numeroActual:22,numerosExtraidos:[22],accion:'extraida'};
 for(const client of wss.clients)client.send(JSON.stringify({...state,type:'STATE_UPDATE'}));
 await wait('document.getElementById("cage").classList.contains("spinning")');
 assert.equal(await evaluate('document.getElementById("currentBall").textContent'),'esperando');
 assert.equal(await evaluate('document.querySelectorAll("#board .called").length'),0);
 await wait('window.locuciones.length === 1');
 assert.equal(await evaluate('document.getElementById("cage").classList.contains("spinning")'),false);
 assert.equal(await evaluate('document.querySelectorAll("#cage .mini-ball").length'),89);
 assert.equal(await evaluate('[...document.querySelectorAll("#cage .mini-ball")].some(b=>b.dataset.numero==="22")'),false);
 console.log('OK: bolillas reales sin duplicados; la extraída desaparece y el reinicio repone todas.');
 console.log('OK: giro 3D antes de revelar la bolilla, sin sonido ni control de audio.');

 assert.deepEqual(await evaluate('window.locuciones'),['Veintidós, los patos.']);
 for(const client of wss.clients){client.send(JSON.stringify({...state,type:'STATE_UPDATE'}));client.send(JSON.stringify({...state,secuencia:12,type:'STATE_UPDATE'}));}
 await new Promise(r=>setTimeout(r,100));
 assert.equal(await evaluate('window.locuciones.length'),1);
 state={...state,secuencia:15,numeroActual:30,numerosExtraidos:[22,25,30]};
 for(const client of wss.clients)client.send(JSON.stringify({...state,type:'STATE_UPDATE'}));
 await wait('document.getElementById("currentBall").textContent === "30"');
 assert.equal(await evaluate('window.locuciones.length'),1);
 console.log('OK: voz exacta una vez; recarga, HTTP, reconexión, duplicados y salto de secuencia permanecen silenciosos.');
 // Los nuevos controles no deben romper la sincronización anterior.
 state={...state,sorteoBingoId:'bingo',secuencia:13,numeroActual:15,numerosExtraidos:Array.from({length:15},(_,i)=>i+1)};
 await cmd('Page.navigate',{url:base+'/sorteo-en-vivo.html?modo=espectador&sorteo=token'});
 await wait('document.getElementById("currentBall")?.textContent === "15"');
 assert.equal(await evaluate('document.getElementById("menuOrganizador").hidden'),true);
 assert.equal(await evaluate('!!document.getElementById("reclamoSerie") || !!document.getElementById("reclamoCarton")'),false);
 assert.equal(await evaluate('document.getElementById("historialCartones").contains(document.getElementById("historial"))'),true);
 await evaluate(`document.getElementById('dniReingreso').value='12345678';document.getElementById('btnCargarSerieEspectador').click()`);
 await wait(`document.querySelectorAll('#cartonesEnVivo [data-serie]').length === 2`);
 assert.deepEqual(await evaluate('(["btnCantarLinea","btnCantarBingo"].map(id=>document.getElementById(id).disabled))'),[false,true]);
 await evaluate('document.getElementById("btnCantarLinea").click()');await wait('document.getElementById("reclamoPublico").textContent.includes("Cartón 2")');
 assert.deepEqual(lastClaim,{tipo:'LINEA',numerosSeries:[1,2]});
 await wait('window.locuciones.at(-1)?.includes("Primera línea validada")');
 assert.deepEqual(await evaluate('(["btnCantarLinea","btnCantarBingo"].map(id=>document.getElementById(id).disabled))'),[false,true]);
 assert.equal(await evaluate('document.getElementById("cartonesEnVivo").hidden'),false);
 assert.match(await evaluate('document.getElementById("ganadoresLista").textContent'),/Ana <script>/);
 assert.equal(await evaluate('document.querySelectorAll("#ganadoresLista script").length'),0);
 state={...state,secuencia:state.secuencia+1,estado:'EN_CURSO',cantos:[]};
 for(const client of wss.clients)client.send(JSON.stringify({...state,type:'STATE_UPDATE'}));
 await wait('!document.getElementById("reclamoPublico").classList.contains("show")');
 assert.match(await evaluate('document.getElementById("ganadoresLista").textContent'),/Ana/);
 await evaluate('document.getElementById("btnCantarLinea").click()');
 await wait('document.getElementById("reclamoPublico").textContent.includes("Segunda línea")');
 assert.equal(lastClaim.tipo,'SEGUNDA_LINEA');
 await wait('window.locuciones.at(-1)?.includes("Segunda línea validada")');
 assert.deepEqual(await evaluate('(["btnCantarLinea","btnCantarBingo"].map(id=>document.getElementById(id).disabled))'),[true,false]);
 await evaluate('document.getElementById("btnCantarBingo").click()');
 await wait('window.document.getElementById("reclamoMsg").textContent.includes("Bingo validado")');
 assert.equal(lastClaim.tipo,'BINGO');
 await wait('window.locuciones.at(-1)?.includes("Bingo validado")');
 assert.deepEqual(await evaluate('(["btnCantarLinea","btnCantarBingo"].map(id=>document.getElementById(id).disabled))'),[true,true]);
 const aviso={id:'aviso1',texto:'Seguimos <b>con bingo</b>',expiraEn:Date.now()+1200};
 for(const client of wss.clients)client.send(JSON.stringify({type:'COMMUNITY_UPDATE',comunidad:{espectadores:23,aviso}}));
 await wait('document.getElementById("audiencia").textContent.includes("23") && !document.getElementById("avisoOrganizador").hidden');
 assert.equal(await evaluate('document.getElementById("avisoOrganizador").textContent'),aviso.texto);
 assert.equal(await evaluate('document.querySelectorAll("#avisoOrganizador b").length'),0);
 await wait('document.getElementById("avisoOrganizador").hidden');
 const locucionesAntes=await evaluate('window.locuciones.length');
 const comunidadVoz={espectadores:23,aviso:{id:'voz-desactivada',texto:'No debe sonar',expiraEn:Date.now()+8000,leerEnVozAlta:true}};
 for(const client of wss.clients)client.send(JSON.stringify({type:'COMMUNITY_UPDATE',comunidad:comunidadVoz}));
 await wait('document.getElementById("avisoOrganizador").textContent === "No debe sonar"');assert.equal(await evaluate('window.locuciones.length'),locucionesAntes);
 await evaluate('document.getElementById("escucharMensajes").click();window.ultimaLocucion.onend?.()');
 comunidadVoz.aviso={...comunidadVoz.aviso,id:'voz-activada',texto:'Seguimos con la siguiente línea'};
 for(const client of wss.clients)client.send(JSON.stringify({type:'COMMUNITY_UPDATE',comunidad:comunidadVoz}));
 await wait('window.locuciones.at(-1) === "Seguimos con la siguiente línea"');
 const leidas=await evaluate('window.locuciones.length');
 for(const client of wss.clients)client.send(JSON.stringify({type:'COMMUNITY_UPDATE',comunidad:comunidadVoz}));
 state={...state,comunidad:comunidadVoz};
 await evaluate('window.dispatchEvent(new Event("focus"))');
 await wait('document.getElementById("conexionEnVivo").textContent === "En vivo"');
 assert.equal(await evaluate('window.locuciones.length'),leidas);
 await evaluate('document.getElementById("escucharMensajes").click()');
 assert.equal(await evaluate('BingoVoz.mensajeActivo()'),false);
 console.log('OK: lectura opcional, un aviso se lee una sola vez y reconectar no lo repite.');
 console.log('OK: aviso temporal seguro, contador, segunda línea e historial conservado al reanudar.');
 console.log('OK: canto sin selectores envía todas las series cargadas y muestra el cartón detectado.');
 await cmd('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await evaluate('document.getElementById("cartonesEnVivo").scrollIntoView();window.scrollBy(0,250)');
 const sticky=await evaluate('({top:document.getElementById("historialCartones").getBoundingClientRect().top,position:getComputedStyle(document.getElementById("historialCartones")).position})');
 assert.equal(sticky.position,'sticky');assert(sticky.top>=-1&&sticky.top<30);
 console.log('OK: historial permanece visible junto a los cartones al desplazarse en pantalla móvil.');
 if (liveOnly) {
   await evaluate('document.getElementById("boardPanel").scrollIntoView()');
   assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'),true);
   await evaluate('document.getElementById("cagePanel").scrollIntoView()');
   const screenshot=await cmd('Page.captureScreenshot',{format:'png'});
   require('node:fs').writeFileSync('/tmp/bingo-community-mobile.png',Buffer.from(screenshot.data,'base64'));
   await evaluate('sessionStorage.setItem("tombolaOrgToken","token-prueba")');
   await cmd('Page.navigate',{url:base+'/sorteo-en-vivo.html?sorteo=room'});
   await wait('document.getElementById("orgControlesBox")?.style.display === "block"');
   await evaluate('document.getElementById("mensajeConVoz").checked=true;document.getElementById("textoMensaje").value="Vamos con el bingo";document.getElementById("btnEnviarMensaje").click()');
   await wait('document.getElementById("mensajeEnvioEstado").textContent === "Mensaje enviado."');
   assert.deepEqual(published,{texto:'Vamos con el bingo',leerEnVozAlta:true});
   assert.equal(await evaluate('document.getElementById("textoMensaje").value'),'');
   await evaluate('document.getElementById("boardPanel").scrollIntoView()');
   await wait('!document.getElementById("avisoOrganizador").hidden');
   const rect=await evaluate('document.getElementById("avisoOrganizador").getBoundingClientRect().top');assert(rect>=0&&rect<100);
   await evaluate('window.confirm=()=>{throw new Error("No debe usar confirm nativo")};document.getElementById("btnReiniciar").click()');
   assert.equal(await evaluate('document.getElementById("confirmarReinicio").hidden'),false);
   await evaluate('document.getElementById("btnCancelarReinicio").click()');assert.equal(resetRequests,0);
   resetFails=true;
   await evaluate('document.getElementById("btnReiniciar").click();document.getElementById("btnConfirmarReinicio").click()');
   await wait('document.getElementById("reinicioEstado").textContent.includes("Servidor no disponible")');
   assert.equal(await evaluate('document.getElementById("btnReiniciar").disabled'),false);
   resetFails=false;
   state={...state,estado:'EN_CURSO',secuencia:state.secuencia+1};
   for(const client of wss.clients)client.send(JSON.stringify({...state,type:'STATE_UPDATE'}));
   await wait('document.getElementById("btnExtraer").textContent === "Extraer bolilla"');
   await evaluate('document.getElementById("btnExtraer").click();document.getElementById("btnReiniciar").click();document.getElementById("btnConfirmarReinicio").click();document.getElementById("btnConfirmarReinicio").click()');
   await wait('document.getElementById("reinicioEstado").textContent.includes("Tablero reiniciado")');
   assert.equal(resetRequests,2);assert.deepEqual(mutationOrder,['extraer','reiniciar']);
   assert.equal(await evaluate('document.querySelectorAll("#board .called").length'),0);
   assert.equal(await evaluate('document.getElementById("currentBall").textContent'),'esperando');
   assert.equal(await evaluate('document.getElementById("reclamoPublico").classList.contains("show")'),false);
   assert.equal(await evaluate('document.getElementById("btnExtraer").disabled'),false);
   console.log('OK: reinicio sin confirm nativo, cancelación, error recuperable, doble clic y extracción pendiente.');
   assert.deepEqual(errors,[]);
   console.log('OK: organizador escribe y envía un aviso visible incluso al desplazarse; vista móvil sin desbordamiento.');
   return;
 }
 await cmd('Page.navigate',{url:base+'/organizador.html'});await wait('!!document.getElementById("btnMostrarRegistro")');
 await evaluate('document.getElementById("btnMostrarRegistro").click();document.getElementById("regPass").value="ClavePrueba123";document.getElementById("regPassRepeat").value="OtraClave";document.getElementById("btnRegistrar").click()');
 await wait('document.getElementById("orgRegistroMsg").textContent.includes("no coinciden")');assert.equal(registrations,0);
 await evaluate('document.querySelector("[data-password-target=regPass]").click()');assert.equal(await evaluate('document.getElementById("regPass").type'),'text');
 await evaluate('document.querySelector("[data-password-target=regPass]").click()');assert.equal(await evaluate('document.getElementById("regPass").type'),'password');
 await evaluate('document.querySelector("[data-password-target=regPassRepeat]").click()');assert.equal(await evaluate('document.getElementById("regPassRepeat").type'),'text');
 await evaluate('document.getElementById("regNombre").value="Prueba";document.getElementById("regEmail").value="prueba@example.test";document.getElementById("regPassRepeat").value="ClavePrueba123";document.getElementById("btnRegistrar").click()');
 await wait('document.getElementById("orgRegistroMsg").textContent.includes("Cuenta creada")');assert.equal(registrations,1);
 console.log('OK: contraseñas distintas bloquean el registro y ambos ojos muestran/ocultan los campos.');
 await evaluate('sessionStorage.setItem("tombolaOrgToken","token-prueba")');
 await cmd('Page.navigate',{url:base+'/sorteo-en-vivo.html'});await wait('document.getElementById("orgSelectBox")?.style.display === "block"');
 assert.equal(await evaluate('document.getElementById("menuOrganizador").hidden'),false);
 assert.equal(await evaluate('document.querySelectorAll("#menuOrganizador a").length'),7);
 await evaluate('document.getElementById("btnNuevoEvento").click()');
 assert.equal(await evaluate('document.getElementById("cagePanel").style.display'),'block');
 assert.equal(await evaluate('["btnExtraer","btnIniciarTablero","autoplayBtn"].every(id=>document.getElementById("cagePanel").contains(document.getElementById(id)))'),true);
 await evaluate('document.querySelector("#menuOrganizador a[href*=crear]").click()');
 await wait('!!document.querySelector("#v-crear.active") && document.getElementById("orgPanel").style.display === "block"');
 console.log('OK: menú de siete opciones, controles dentro del bolillero y sesión conservada al volver a crear sorteo.');
 for (const tipo of ['numeros','series']) {
   await evaluate(`window.confirm=()=>true;tableroOrganizadorSorteoId='pagos';tableroOrganizadorTipo='RIFA';document.getElementById('${tipo==='numeros'?'tableroToken':'seriesToken'}').value='token';${tipo==='numeros'?'cargarTablero':'cargarSeries'}()`);
   const selector=tipo==='numeros'?'#tablero-grid .ball':'#series-grid .serie-chip';
   await wait(`!!document.querySelector('${selector}')`);
   const ficha=tipo==='numeros'?'#tableroContenido':'#seriesShell';
   await evaluate(`document.querySelector('${selector}').click();window.confirm=()=>false;document.querySelector('${ficha} [data-estado=LIBRE]').click()`);
   const antes=pagos.length;
   assert.equal(reservas[tipo],'RESERVADO');
   await evaluate(`window.confirm=()=>true;document.querySelector('${ficha} [data-estado=LIBRE]').click()`);
   await wait(`document.querySelector('${selector}').classList.contains('libre')`);
   assert.equal(pagos.length,antes+1);assert.equal(pagos.at(-1).estado,'LIBRE');
   reservas[tipo]='RESERVADO';
   await evaluate(`${tipo==='numeros'?'cargarTablero':'cargarSeries'}()`);
   await wait(`document.querySelector('${selector}').classList.contains('reservado')`);
   const inicial=pagos.length;
   await evaluate(`document.querySelector('${selector}').click()`);
   assert.equal(pagos.length,inicial);
   assert.match(await evaluate(`document.querySelector('${tipo==='numeros'?'#tableroContenido':'#seriesShell'} .titular-seleccionado')?.textContent || document.querySelector('.titular-seleccionado').textContent`),/Titular Prueba.*12345678/);
   if(tipo==='series') {
     await evaluate(`document.querySelector('${selector}').dispatchEvent(new PointerEvent('click',{pointerType:'touch',detail:1,bubbles:true}))`);
     assert.equal(pagos.length,inicial);
     await evaluate(`document.querySelector('${selector}').dispatchEvent(new PointerEvent('click',{pointerType:'touch',detail:1,bubbles:true}))`);
   } else await evaluate(`document.querySelector('${selector}').dispatchEvent(new MouseEvent('click',{detail:2,bubbles:true}))`);
   await wait(`document.querySelector('${selector}').classList.contains('tomado')`);
   assert.equal(pagos.length,inicial+1);assert.equal(pagos.at(-1).estado,'TOMADO');
   await evaluate(`document.querySelector('${selector}').dispatchEvent(new MouseEvent('click',{detail:2,bubbles:true}))`);
   assert.equal(pagos.length,inicial+1);
 }
 console.log('OK: un clic muestra titular y DNI sin cobrar; doble clic paga una sola vez en rifa y bingo, sin liberar compras pagadas.');
 assert.deepEqual(errors,[]);
 } finally {
   if(ws)ws.close();chrome.kill();await once(chrome,'exit');
   for(const client of wss.clients)client.terminate();await new Promise(r=>wss.close(r));await new Promise(r=>server.close(r));
   await rm(profile,{recursive:true,force:true,maxRetries:20,retryDelay:250});
 }
})().catch(error=>{console.error(error);process.exitCode=1});
