// Prueba de la vista real en Chromium mediante CDP, con servidor de sala controlado.
const assert = require('node:assert/strict');
const express = require('express');
const http = require('node:http');
const {once} = require('node:events');
const {spawn} = require('node:child_process');
const {mkdtempSync} = require('node:fs');
const {rm} = require('node:fs/promises');
const {tmpdir} = require('node:os');
const path = require('node:path');
const WebSocket = require('ws');
const state = {salaId:'room',secuencia:5,numeroActual:5,numerosExtraidos:[1,2,3,4,5],bolillas:[1,2,3,4,5],ronda:0,
 modo:'BINGO',titulo:'Bingo de prueba',rangoMax:90,estado:'EN_CURSO',conteos:{},sorteoBingoId:null,timestamp:new Date().toISOString()};
const app = express();app.use(express.json());let registrations=0;
const testCard={id:'card-2',posicion:2,contenido:[[1,2,3,4,5,null,null,null,null],[6,7,8,9,10,null,null,null,null],[11,12,13,14,15,null,null,null,null]]};
app.post('/auth/registro',(_q,r)=>{registrations++;r.json({mensaje:'Cuenta creada'});});
let eliminados=0;
app.get('/auth/me',(_q,r)=>r.json({id:'org',nombre:'Ana Pérez',email:'ana@example.test',rol:'ORGANIZADOR',estado:'APROBADO'}));
app.get('/sorteos',(_q,r)=>r.json(eliminados?[]:[{id:'sorteo-prueba',titulo:'Bingo para eliminar',tipo:'BINGO',estado:'BORRADOR'}]));
app.delete('/sorteos/sorteo-prueba',(_q,r)=>{eliminados++;r.json({mensaje:'Sorteo eliminado'});});
app.get('/vivo/:token',(_q,r)=>r.set('Cache-Control','no-store').json({type:'STATE_SNAPSHOT',...state}));
const identidad={nombre:'Ana Pérez',dni:'12345678',telefono:'+54 11 12345678'};
app.get(['/s/:token/organizador','/vivo/:token/organizador'],(_q,r)=>r.json(identidad));
const cantos=[{tipo:'LINEA',participante:'María Gómez',numeroSerie:2,numeroCarton:2,ronda:0,contenido:testCard.contenido,bolillas:[1,2,3,4,5],cantadoEn:'2026-09-09T15:00:00Z',evento:{titulo:'Bingo prueba'}},{tipo:'BINGO',participante:'Juan López',numeroSerie:3,numeroCarton:1,ronda:0,contenido:testCard.contenido,bolillas:Array.from({length:15},(_,i)=>i+1),cantadoEn:'2026-09-09T15:02:00Z',evento:{titulo:'Bingo prueba'}}];
app.get(['/s/:token/resultado','/vivo/:token/resultados'],(_q,r)=>r.json({tipo:'BINGO',titulo:'Bingo prueba',cantos}));
app.use(express.static(path.resolve(__dirname,'../frontend')));
(async()=>{
 const server = http.createServer(app);const wss = new WebSocket.WebSocketServer({server,path:'/ws'});
 wss.on('connection',ws=>{ws.on('message',raw=>{const msg=JSON.parse(raw);if(msg.type==='RESYNC')ws.send(JSON.stringify({type:'STATE_SNAPSHOT',...state}));if(msg.type==='PING')ws.send(JSON.stringify({type:'PONG'}));});});
 server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;
 const profile = mkdtempSync(path.join(tmpdir(),'bingo-live-'));
 const chrome=spawn(process.env.CHROMIUM_PATH || '/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
 let ws;
 try {
 const debuggerUrl=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(new Error('Chromium no inició')),15000);chrome.stderr.on('data',chunk=>{output+=chunk;const m=output.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1]);}});chrome.on('error',reject);});
 const debugBase=new URL(debuggerUrl).origin.replace('ws:','http:');const targets=await (await fetch(debugBase+'/json')).json();
 ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await once(ws,'open');let id=0;const calls=new Map(),errors=[];
 ws.on('message',raw=>{const m=JSON.parse(raw);if(m.id){calls.get(m.id)?.(m);calls.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);});
 const cmd=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;calls.set(key,m=>m.error?reject(m.error):resolve(m.result));ws.send(JSON.stringify({id:key,method,params}));});
 const evaluate=async expression=>{const r=await cmd('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=async expr=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await new Promise(r=>setTimeout(r,100));}throw new Error('Timeout '+expr);};
 await cmd('Page.enable');await cmd('Runtime.enable');await cmd('Network.enable');
 await cmd('Page.navigate',{url:base+'/resultado-publico.html?sorteo=token'});
 await wait('document.querySelectorAll(".resultado-canto").length === 2');
 await wait('document.getElementById("datosOrganizador")?.textContent.includes("12345678")');
 assert.match(await evaluate('document.getElementById("contenido").textContent'),/María Gómez/);
 assert.match(await evaluate('document.getElementById("contenido").textContent'),/Juan López/);
 assert.equal(await evaluate('document.querySelectorAll(".resultado-celdas .extraida").length'),20);
 await cmd('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'),true);
 await cmd('Page.navigate',{url:base+'/sorteo-en-vivo.html?modo=espectador&sorteo=token'});
 await wait('document.getElementById("datosOrganizador")?.textContent.includes("Ana Pérez")');
 await evaluate('document.getElementById("enlaceResultados").click()');
 await wait('document.querySelectorAll(".resultado-canto").length === 2');
 assert.equal(await evaluate('new URL(location.href).searchParams.get("evento")'),'1');
 await cmd('Page.navigate',{url:base+'/'});
 await wait('!!document.getElementById("crearCuenta")');
 await evaluate('document.getElementById("password").value="Clave123";document.getElementById("mostrarLoginPassword").click()');
 assert.equal(await evaluate('document.getElementById("password").type'),'text');
 assert.equal(await evaluate('document.getElementById("password").value'),'Clave123');
 assert.equal(await evaluate('document.getElementById("mostrarLoginPassword").getAttribute("aria-pressed")'),'true');
 await evaluate('document.getElementById("mostrarLoginPassword").click()');
 assert.equal(await evaluate('document.getElementById("password").type'),'password');
 await evaluate('document.getElementById("crearCuenta").click()');
 await evaluate('document.getElementById("nombre").value="Ana Pérez";document.getElementById("registroEmail").value="ana@example.test";document.getElementById("registroPassword").value="Password123";document.getElementById("repetirPassword").value="Password123"');
 assert.equal(await evaluate('document.getElementById("registro").checkValidity()'),false);
 await evaluate('document.getElementById("dni").value="12345678";document.getElementById("telefono").value="1123456789"');
 assert.equal(await evaluate('document.getElementById("registro").checkValidity()'),true);
 await evaluate('document.getElementById("registro").requestSubmit()');
 await wait('document.getElementById("mensaje").textContent.includes("Cuenta creada")');
 assert.equal(registrations,1);
 await evaluate('sessionStorage.setItem("tombolaOrgToken","token-prueba")');
 await cmd('Page.navigate',{url:base+'/organizador.html'});
 await wait('!!document.querySelector("#misSorteosGrid .btn-danger")');
 await evaluate('window.confirm=()=>false;document.querySelector("#misSorteosGrid .btn-danger").click()');
 assert.equal(eliminados,0);
 await evaluate('window.confirm=()=>true;document.querySelector("#misSorteosGrid .btn-danger").click()');
 await wait('document.querySelectorAll("#misSorteosGrid .sorteo-card").length === 0 && !!document.querySelector("#misSorteosGrid .add-card")');
 assert.equal(eliminados,1);
 assert.deepEqual(errors,[]);
 console.log('OK: resultados con dos titulares y cartones, identificación pública, navegación desde vivo, diseño móvil, registro obligatorio, ojito del login y eliminación con confirmación.');
 } finally {
   if(ws)ws.close();chrome.kill();await once(chrome,'exit');
   for(const client of wss.clients)client.terminate();await new Promise(r=>wss.close(r));await new Promise(r=>server.close(r));
   await rm(profile,{recursive:true,force:true,maxRetries:20,retryDelay:250});
 }
})().catch(error=>{console.error(error);process.exitCode=1});
